### ISSUE TITLE
Docs won't build locally with latest sphinx-autoapi in fresh environment

### ISSUE THREAD

**Issue by garrison** [jcmgray/quimb#261]
### What happened?

I tried to build the docs locally in a fresh clone and virtualenv:

```sh
git clone [...]
cd quimb/docs
pip install '..[docs]'
make html
```

but I received an error.

```
Extension error (autoapi.extension):
Handler <function run_autoapi at 0x7f658abf6660> for event 'builder-inited' threw an exception (exception: module 'sphinx.util' has no attribute 'status_iterator')
make: *** [Makefile:20: html] Error 2
```

Everything works if I downgrade to sphinx-autoapi==3.2.0 from the latest (3.3.1).  I have not yet tried intermediate versions in a fresh clone.

### Anything else we need to know?

I opened this issue to track it, and also in case you ever witness the same problem.  I am not necessarily asking you to fix it.

### Environment

I am building from the `main` branch.  I experienced this on both an RHEL system and in an Ubuntu container.

**Comment by garrison** [comment]
>  I have not yet tried intermediate versions in a fresh clone.

Update: I was able to get it to work with `sphinx-autoapi==3.3.0`.  The only substantial change between the two releases appears to be https://github.com/readthedocs/sphinx-autoapi/commit/5d53f92a0ce8547e23ef40ab49b307d09d2cc251.

**Comment by jcmgray** [comment]
Thanks for the issue and looking into different versions @garrison! 

It does seem to be some upstream problem but may be worth pinning some versions for the docs build. 

Keeping this open for the moment.

**Comment by jcmgray** [comment]
Closing for the moment as docs seem to be working currently.
